#!/usr/bin/env php
<?php

use Kirby\Cms\App;
use Kirby\Retour\Retour;
use Kirby\Toolkit\Str;

// check if we are indeed on the command line
if (php_sapi_name() !== 'cli') die();

// Bootstrap
require __DIR__ . '/../tests/bootstrap.php';

$app    = new App(['roots' => ['index' => __DIR__ . '/../../../../']]);
$retour = Retour::instance($app);
$retour->log()->flush('all');

$redirects = [
    'leistungen/(:all)',
    'team',
    'jobs',
    'jobs/(:all)',
    'en'
];

$referrers = [
    Str::random(10),
    Str::random(15),
    Str::random(7),
    Str::random(8),
    Str::random(16),
    Str::random(10),
    Str::random(5)
];

$start = strtotime('-25 month');
$end   = strtotime('today');

for ($i=0; $i < 50000; $i++) {
    $time     = rand($start, $end);
    $redirect = rand(0, 9) > 5 ? $redirects[array_rand($redirects)] : null;

    $retour->log()->add([
        'date'     => date('Y-m-d H:i:s', $time),
        'path'     => $path = Str::random(10),
        'redirect' => $redirect,
        'referrer' => rand(0, 9) > 7 ? $referrers[array_rand($referrers)] : null
    ]);

    // only resolve failure records (no redirect set)
    if ($redirect === null && rand(0, 15) > 12) {
        $retour->log()->resolve($path);
    }
}

exit(0);
